name: Scheduled Trading Alerts

# Run every 30 minutes UTC → London runs every 30 minutes (BST or GMT)
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  send-signals:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance requests pytz

      - name: Export Telegram credentials
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}"   >> $GITHUB_ENV

      - name: Run trading signals script
        run: |
          python trade_alerts.py
