name: "Scheduled Trading Alerts"

on:
  # Run at 07:00 UTC (08:00 BST), Monday–Friday
  schedule:
    - cron: '0 7 * * 1-5'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  daily-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz requests

      - name: Send Daily Telegram Trading Alert
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python trading_alerts.py
