name: Scheduled Trading Alerts

on:
  schedule:
    # Forex/Stocks alerts: Every 2 hours at minute 0, from 07:00–22:00 UTC (08:00–23:00 London), Mon–Fri
    - cron: '0 7-22/2 * * 1-5'
    # Crypto alerts: Every 2 hours at minute 0, every day
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  send-signals:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance requests pytz
      - name: Export Telegram credentials
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      - name: Run trading alerts
        run: python trading_alerts.py

  crypto-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install crypto dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas requests

      - name: Export Telegram credentials
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      - name: Run crypto alerts
        run: python CryptoAlert.py

  second-crypto-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install crypto dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas requests

      - name: Export Telegram credentials
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      - name: Run second crypto alerts
        run: python 2ndcrypto.py
